#!/bin/sh

set -e

echo ""
echo "  Ealden's Shell Config"
echo ""

# Check if Homebrew is present
if test ! $(which brew); then
  echo "  x You need to install Homebrew:"
  echo "    ruby -e \"\$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)\""
  exit
else
  echo "  + Homebrew found."
fi

# Install Homebrew packages
echo "  + Installing Homebrew packages"
brew install git
brew install bash-completion
brew install rbenv
brew install ruby-build
brew install pyenv
brew install postgresql
brew install ag
brew install hub 
brew install macvim

# Install PHP packages
echo "  + Installing PHP packages"
#brew tap josegonzalez/php
#brew tap homebrew/dupes
brew install php54
brew install phpunit
brew install composer

# Set up symlinks
echo "  + Setting up symlinks"
rake

echo ""
echo "  We're ready to rock!"
