#!/bin/sh

set -e

echo ""
echo "  Ealden's Shell Config"
echo ""

# Check if Homebrew is present
if test ! $(which brew); then
  echo "  x You need to install Homebrew:"
  echo "    ruby -e \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\""
  exit
else
  echo "  + Homebrew found."
fi

# Install Homebrew packages
echo "  + Installing Homebrew packages..."
brew install git
brew install bash-completion
brew install rbenv
brew install ruby-build
brew install ag
brew install wget
brew install jsonpp 
brew install dos2unix
brew install node

brew install postgresql
ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist

brew install redis
ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist

brew linkapps

# Set up symlinks
echo "  + Setting up symlinks..."
rake

echo ""
echo "  We're ready to rock!"
