#!/bin/sh

set -e

echo ""
echo "  Ealden's Shell Config"
echo ""

# Check if Homebrew is present
if test ! $(which brew); then
  echo "  x You need to install Homebrew:"
  echo "    ruby -e \"\$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)\""
  exit
else
  echo "  + Homebrew found."
fi

# Install Homebrew packages
echo "  + Installing Homebrew packages..."
brew install git
brew install bash-completion
brew install rbenv
brew install ruby-build
brew install rbenv-gem-rehash 
brew install pyenv
brew install postgresql
brew install ag
brew install hub 
brew install macvim
brew install node
brew install wget
brew install jsonpp 
brew install dos2unix
brew install bats

brew install redis
ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist

brew install hg
brew install tmux

# Set up symlinks
echo "  + Setting up symlinks..."
rake
brew linkapps

echo ""
echo "  We're ready to rock!"
